---
- name: install pip
  apt:
    name: python-pip
    update_cache: yes
  tags: [always]

- name: update pip to latest
  pip:
    name: pip
    state: latest
  tags: [always]

- name: install docker python module
  pip:
    name: docker
    state: latest
  tags: [always]

- name: install docker-compose python module
  pip:
    name: docker-compose
    state: latest
  tags: [always]

- name: pull the keycloak image
  docker_image:
    name: "{{ KEYCLOAK_DOCKER_IMAGE }}:{{ KEYCLOAK_DOCKER_IMAGE_TAG }}"
    #source: pull
    pull: yes
  tags: [always]

- name: get stat information on the docker-compose file
  stat:
    path: "{{ KEYCLOAK_DIST_DIR }}/docker-compose.yml"
  register: dc_st

- name: ensure that the existing deployment is not running if applicable
  docker_compose:
    project_src: "{{ KEYCLOAK_DIST_DIR }}"
    state: absent
  when: dc_st.stat.isreg is defined and dc_st.stat.isreg
  tags: [always]

- name: verify that the KEYCLOAK_DIST_DIR exists
  file:
    path: "{{ KEYCLOAK_DIST_DIR }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [always]

- name: copy the docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ KEYCLOAK_DIST_DIR }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags: [always]

- name: (dev only) copy the docker-compose dev file
  template:
    src: docker-compose.dev.yml.j2
    dest: "{{ KEYCLOAK_DIST_DIR }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags: [never, dev]

- name: spin up containers
  docker_compose:
    project_src: "{{ KEYCLOAK_DIST_DIR }}"
    state: present
  tags: [always]

- import_tasks: dev.yml
  tags: [never, dev]
